# Generated by Django 2.2 on 2019-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
